// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_entitlement.
// - Entity ID: 102019c98fff79679fd8e5ee842c6ed082f.
// - Entity Version: 102019c9914440d7cbe91d7d44d67b3e2c0.
// - Task ID: 69a0050512e4a83b51656229.
// - Task Root ID: 699a7e02c62b8b13bb143e71.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for UserEntitlementBillingPeriod
 */
export enum UserEntitlementBillingPeriod {
  Unspecified = 0,
  Monthly = 1,
  Yearly = 2,
}
/**
 * Enumeration for UserEntitlementPlanTier
 */
export enum UserEntitlementPlanTier {
  Unspecified = 0,
  Free = 1,
  Pro = 2,
  Premium = 3,
}



/**
 * Interface for UserEntitlementModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserEntitlementModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  plan_tier: UserEntitlementPlanTier;
  billing_period: UserEntitlementBillingPeriod;
  stripe_session_id?: string | null;
  expires_at?: string | null;
}

/**
 * ORM class for UserEntitlement entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserEntitlementORM {
  private static instance: UserEntitlementORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c98fff79679fd8e5ee842c6ed082f';
    this.entityName = 'user_entitlement';
    this.entityVersion = '102019c9914440d7cbe91d7d44d67b3e2c0';
    this.taskId = '69a0050512e4a83b51656229';
    this.taskRootId = '699a7e02c62b8b13bb143e71';
  }

  /**
   * Get singleton instance of UserEntitlementORM
   */
  public static getInstance(): UserEntitlementORM {
    if (!UserEntitlementORM.instance) {
      UserEntitlementORM.instance = new UserEntitlementORM();
    }
    
    return UserEntitlementORM.instance;
  }

  /**
   * Get user_entitlement by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getUserEntitlementByIDs(ids: string[]): Promise<UserEntitlementModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_entitlement by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteUserEntitlementByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all UserEntitlement records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserEntitlement(): Promise<UserEntitlementModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserEntitlement record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserEntitlement(data: UserEntitlementModel[]): Promise<UserEntitlementModel[]> {
    const structured = data.map((item) => CreateData(UserEntitlementModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserEntitlement records
   */
  async purgeAllUserEntitlement(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserEntitlement records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserEntitlement(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserEntitlementModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_entitlement by Id index
   * This function gets data by index.
   */
  async getUserEntitlementById(
    id: string,
  ): Promise<UserEntitlementModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_entitlement by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserEntitlementById(
    id: string,
    data: UserEntitlementModel
  ): Promise<UserEntitlementModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserEntitlementModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_entitlement by Id index
   */
  async deleteUserEntitlementById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_entitlement by DataCreator index
   * This function gets data by index.
   */
  async getUserEntitlementByDataCreator(
    data_creator: string,
  ): Promise<UserEntitlementModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_entitlement by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserEntitlementByDataCreator(
    data_creator: string,
    data: UserEntitlementModel
  ): Promise<UserEntitlementModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserEntitlementModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_entitlement by DataCreator index
   */
  async deleteUserEntitlementByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_entitlement by DataUpdater index
   * This function gets data by index.
   */
  async getUserEntitlementByDataUpdater(
    data_updater: string,
  ): Promise<UserEntitlementModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_entitlement by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserEntitlementByDataUpdater(
    data_updater: string,
    data: UserEntitlementModel
  ): Promise<UserEntitlementModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserEntitlementModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_entitlement by DataUpdater index
   */
  async deleteUserEntitlementByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_entitlement by UserId index
   * This function gets data by index.
   */
  async getUserEntitlementByUserId(
    user_id: string,
  ): Promise<UserEntitlementModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_entitlement by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserEntitlementByUserId(
    user_id: string,
    data: UserEntitlementModel
  ): Promise<UserEntitlementModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = UserEntitlementModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_entitlement by UserId index
   */
  async deleteUserEntitlementByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserEntitlementModel data array
   */
  private resultToData(values: Data[]): UserEntitlementModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserEntitlementModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserEntitlementModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserEntitlementModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserEntitlementModel => item !== null);
  }
}

/**
 * Convert UserEntitlementModel data to Value array
 */
function UserEntitlementModelToValues(data: UserEntitlementModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'plan_tier', type: DataType.enumeration, defaultValue: 0 },
    { key: 'billing_period', type: DataType.enumeration, defaultValue: 0 },
    { key: 'stripe_session_id', type: DataType.string, defaultValue: null },
    { key: 'expires_at', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserEntitlementModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserEntitlementModel data
 */
function UserEntitlementModelFromValues(values: Value[]): UserEntitlementModel {
  const data: Partial<UserEntitlementModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'plan_tier':
        data.plan_tier = ParseValue(value, DataType.enumeration) as UserEntitlementPlanTier;
        break;
      case 'billing_period':
        data.billing_period = ParseValue(value, DataType.enumeration) as UserEntitlementBillingPeriod;
        break;
      case 'stripe_session_id':
        data.stripe_session_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'expires_at':
        data.expires_at = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as UserEntitlementModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}

export default UserEntitlementORM;