/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as BillingCancelRouteImport } from './routes/billing.cancel'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/welcome'
    | '/billing/cancel'
    | '/billing/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/welcome'
    | '/billing/cancel'
    | '/billing/success'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/welcome'
    | '/billing/cancel'
    | '/billing/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
